name: Create release pull request

on:
  push:
    branches:
      - develop

jobs:
  git_pr_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          ruby-version: 3.1

      - name: create-pr
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
        run: |
          gem install git-pr-release -v "2.2.0"
          git-pr-release --json
