name: Add label attached issue to project

on:
  issues:
    types: [opened, reopened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        env:
          LABEL_NAME_A: ${{ github.event.label.name }}
          LABEL_NAME_B: ${{ github.event.issue.label }}
          LABEL_NAME_C: ${{ contains(github.event.issue.labels.*.name, 'HOGE 作業依頼') }}
        run: |
          echo "$LABEL_NAME_A"
          echo "$LABEL_NAME_B"
          echo "$LABEL_NAME_C"
