name: Add label attached issue to project

on:
  issues:
    types: [opened, reopened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            const labelNames = "${{ toJSON(github.event.issue.labels.*.name) }}";
            console.log(labelNames);
            const projectId = "PVT_kwHOAJiWTs4ASybS";
            console.log(projectId);
            const issueNumber = "${{ github.event.issue.number }}";
            console.log(issueNumber);
            const ownerRepo = "${{ github.repository }}";
            console.log(ownerRepo);
