name: Test
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Hello from test env. ${{ secrets.TOKEN }}
