name: Test
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: development
    steps:
      - name: Echo
        run: echo Hello from test env. ${{ secrets.HAPPY_BOX }}
