name: Test
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Echo
        run: |
            echo Hello from test env. ${{ secrets.HAPPY_BOX }}
            echo '${{ github.event.pull_request.node_id }}'
            echo '${{ github.event.pull_request.title }}'
            echo '${{ github.event.pull_request.merged_at }}'
